version: '3.7'

services:
  app:
    build:
      target: develop
    ports:
      - 5000:5000
    depends_on:
      - dbserver
    command: "uvicorn main:app --host 0.0.0.0 --port 5000 --reload --header \"content-security-policy:default-src 'self'\""

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    command: python test_runner.py
