version: '3.7'

services:
  app:
    container_name: diminish_app
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    ports:
      - 9099:5000
    volumes:
      - .:/app
    depends_on:
      - dbserver

  dbserver:
    image: mongo:4.2.1
    restart: always
    ports:
      - 27000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
