version: '3.7'

services:
  app:
    build:
      target: production
      dockerfile: ./ops/Dockerfile
      context: ..
    ports:
      - 9099:5000
    volumes:
      - ..:/app
    depends_on:
      - dbserver

  dbserver:
    image: mongo:4.4.1
    restart: unless-stopped
    ports:
      - 27000:27017
    volumes:
      - ../../db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
