version: '3.7'

services:
  app:
    build:
      dockerfile: ./ops/Dockerfile
      context: ..
    depends_on:
      - dbserver
    command: "uvicorn main:app --host 0.0.0.0 --port 5000 --reload --header \"content-security-policy:default-src 'self'\""

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../public:/usr/share/nginx/html
    ports:
      - 8088:80
    depends_on:
      - app
