version: '3.7'

services:
  app:
    build:
      dockerfile: ./ops/Dockerfile
      context: ..
    ports:
      - 9099:5000
    depends_on:
      - dbserver
    command: "uvicorn main:app --host 0.0.0.0 --port 5000 --reload --header \"content-security-policy:default-src 'self'\""
